zookeeper:
  image: bobrik/zookeeper
  hostname: zookeeper
  ports:
   - "2181:2181"
  environment:
    ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
    ZK_ID: 1

master:
  image: mesosphere/mesos-master:0.23.0-1.0.ubuntu1404
  hostname: master
#  net: host
  ports:
   - "5050:5050"
  links:
    - zookeeper:zookeeper
  environment:
    MESOS_ZK: zk://zookeeper:2181/mesos
    MESOS_HOSTNAME: master
#    MESOS_IP: 0.0.0.0
    MESOS_QUORUM: 1
    MESOS_CLUSTER: docker-compose
    MESOS_WORK_DIR: /var/lib/mesos

slave:
  image: mesosphere/mesos-slave:0.23.0-1.0.ubuntu1404
#  net: host
#  pid: host
  hostname: slave
  ports:
   - "5051:5051"
  links:
    - zookeeper:zookeeper
    - master:master
  environment:
    MESOS_MASTER: zk://zookeeper:2181/mesos
    MESOS_HOSTNAME: master
#    MESOS_IP: 127.0.0.1
    MESOS_CONTAINERIZERS: docker,mesos
    MESOS_ISOLATOR: cgroups/cpu,cgroups/mem
    MESOS_LOG_DIR: /var/log
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /usr/local/bin/docker:/usr/bin/docker
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
    - /sys:/sys:ro
    - mesosslace-stuff:/var/log

marathon:
  image: mesosphere/marathon:v0.10.1
  hostname: marathon
  ports:
   - "8123:8080"
#  net: host
  links:
    - zookeeper:zookeeper
    - master:master
    - slave:slave
  environment:
    MARATHON_MASTER: zk://zookeeper:2181/mesos
    MARATHON_ZK: zk://zookeeper:2181/marathon
    MARATHON_HOSTNAME: marathon
